language: node_js
node_js:
- stable
deploy:
  - provider: script
    script: npm install -g now && now --token=$NOW_TOKEN && now --token=$NOW_TOKEN alias cserdean.me
    on:
      branch: master
  - provider: script
    script: npm install -g now && now --token=$NOW_TOKEN && now --token=$NOW_TOKEN alias dev.cserdean.me
    on:
      branch: master
