version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.12

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install now cli
          command: sudo npm install --global --unsafe-perm now
      - deploy:
          name: Deploy and alias
          command: ls && now --token $ZEIT_TOKEN && now alias $([ "$CIRCLE_BRANCH" == "master" ] && echo "cserdean.me" || echo "$CIRCLE_BRANCH.cserdean.me") --token $ZEIT_TOKEN

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
